const i18nMessages = {
  web_link: "线上链接",
  material: "参考资料",
  homework: "作业",
  forum: "讨论",
  online_video: "音视频教材",
  slide: "微课",
  lesson: "录播教材",
  lesson_replay: "教室录播",
  exam: "测试",
  chatroom: "iSlide 直播",
  classroom: "随堂测试",
  questionnaire: "调查问卷",
  page: "页面",
  scorm: "第三方教材",
  interaction: "互动教材",
  feedback: "教学反馈",
  virtual_classroom: "Connect 直播",
  zoom: "Zoom 直播",
  microsoft_teams_meeting: "Teams 直播",
  webex_meeting: "Webex 直播",
  welink: "Welink",
  tencent_meeting: "课堂直播",
  classin: "ClassIn 直播",
  live_record: "直播",
  select_student: "选人",
  race_answer: "抢答",
  number_rollcall: "数字点名",
  qr_rollcall: "二维码点名",
  dingtalk_meeting: "钉钉会议",
};
